### ISSUE TITLE
[sveltekit-pod] IssueSearchAssignees.svelte: Remove `!important` from SCSS

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#967]
File: svelte-kit-scss/src/lib/components/IssueSearch/IssueSearchListItem/IssueSearchAssignees.svelte
- look into removing the `!important` from the `margin-right` property
`!important` is almost never the right solution. It has overreaching implications of overriding user styles and limits the ability to override styles in the future. Since this is a showcase app, showing our expertise is important, and I don't think `!important` in the CSS reflects well on us.

**Comment by BigAB** [comment]
The same effect could be achieved with a css custom property/variable like:

```svelte
    {#each assigneesReversed as assignee, index}
      <div
        class="assignee"

        style={`--squish-margin: ${computeMarginRightPx(itemSizePx, index)}px`}

        class:last={index === assigneesCount - 1}
      >
        <img class="image" src={assignee.avatarUrl} alt={assignee.login} />
      </div>
    {/each}
```

```css
      &:hover {
        .assignee {
          margin-right: 4px;
          &.last {
            margin-right: 0px;
          }
        }
      }
      .assignee {
       ...
        margin-right: var(--squish-margin, 0px);
        ...
      }
```
